services:
  server:
    container_name: dd-quiz
    build:
      context: .
    command: node ./server/dist/index.js
    restart: always
    ports:
      - '3004:8003'
    environment:
      PORT: '8003'
      MAILER_PORT: '465'
      MAILER_HOST: 'smtp.mail.ru'
      MAILER_USER: ''
      MAILER_PASSWORD: ''
      MAILER_DESTINATION: ''
